name: github pages

on:
  push:
    branches:
      - main

jobs:
  build-gh-pages:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Setup nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        cache: npm

    - name: Install dependencies npm modules
      run: npm install

    - name: Build pages
      run: |
        npm run build
        npm run export
        touch ./out/.nojekyll  # to read _next/

    - name: Deploy pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out